// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContactsAPI.Models
{
    public partial class Contact
    {
        public Contact()
        {
            ContactSkills = new HashSet<ContactSkill>();
        }

        public int Id { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string Fullname { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string MobilePhoneNumber { get; set; }

        public virtual ICollection<ContactSkill> ContactSkills { get; set; }
    }
}