// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContactsAPI.Models
{
    public partial class ContactSkill
    {
        public int ContactId { get; set; }
        public int SkillId { get; set; }
        public string ExpertiseLevel { get; set; }

        public virtual Contact Contact { get; set; }
        public virtual Skill Skill { get; set; }
    }
}